#!/usr/bin/env php

<?php

    chdir(dirname(__FILE__));

    $list = array_filter(explode(PHP_EOL, `ls -d */dist`));

    foreach ($list as $item)
    {
        echo 'Merge Component '.str_replace('/dist', '', $item).PHP_EOL;
        echo `mkdir -p ../alxw_judge_system/View/${item}`;
        echo `cp -rvf ${item}/* ../alxw_judge_system/View/${item}/`;
    }

?>
