#!/bin/bash

NAME=$1

if [ $# == 0 ];
then
    echo -n 'Please input dir name:'
    read NAME;
fi

echo 'Make dir...'
mkdir $NAME
echo 'Maked !'

echo 'Copy files...'
yes n | cp -riv Template/* $NAME/
echo 'Copied !'

echo 'Install scripts ...'
cd $NAME
cnpm install
echo 'Installed !'

echo 'Finished !'
